version: '2'
services:
    demo-application-v1:
        image: markoniemi/traefik-consul-demo
        environment:
            - CONSUL_HOST=${CONSUL_HOST}
            - CONSUL_PORT=${CONSUL_PORT}
            - VERSION=${VERSION}
            - PATH_PREFIX=${PATH_PREFIX}
        networks:
            - backend
networks:
    backend:
        external:
            name: traefik-consul-demo_backend
