version: '2'
services:
    demo-service-v2:
        image: markoniemi/demo-service
        environment:
            - CONSUL_HOST=${CONSUL_HOST}
            - CONSUL_PORT=${CONSUL_PORT}
            - VERSION=v2
            - PATH_PREFIX=/demo/v2
        networks:
            - backend
networks:
    backend:
        external:
            name: traefik-consul-demo_backend
