version: '2'
services:
    traefik:
        image: traefik:v1.7.5
        command:
            - "--api"
            - "--consulCatalog" #Enable Consul Catalog Provider.
            - "--consulCatalog.endpoint=consul:8500" #Consul server endpoints
            - "--consulCatalog.exposedByDefault=false" #Expose Consul catalog services by default in Traefik.
            - "--consulCatalog.stale=false" #Allow Consul server to serve the catalog reads regardless of whether it is the leader.
            - "--consulCatalog.domain=consul.localhost" #Default base domain used for the frontend rules.
            - "--consulCatalog.prefix=traefik" #Prefix for Consul catalog tags.
            - "--logLevel=DEBUG"
        ports:
            - 80:80     #The HTTP port
            - 8080:8080 #The Web UI (enabled by --api)
        networks:
            - microservices
    consul:
        image: consul:1.5.1
        ports:
            - 8301:8301 #LAN Serf: The Serf LAN port (TCP and UDP)
            - 8302:8302 #Wan Serf: The Serf WAN port TCP and UDP)
            - 8300:8300 #server: Server RPC address (TCP Only)
            - 8500:8500 #HTTP: The HTTP API (TCP Only)
            - 8600:53/udp #DNS: The DNS server (TCP and UDP)
        command: consul agent -server -dev -client=0.0.0.0 -ui -bootstrap -log-level debug
        networks:
            - microservices
    demo-application-8082:
        image: markoniemi/traefik-consul-demo
        environment:
            - PORT=8082
            - CONSUL_HOST=${CONSUL_HOST}
            - CONSUL_PORT=${CONSUL_PORT}
            - PATH_PREFIX=${PATH_PREFIX}
        ports:
            - 8082:8082
        networks:
            - microservices
    demo-application-8083:
        image: markoniemi/traefik-consul-demo
        environment:
            - PORT=8083
            - CONSUL_HOST=${CONSUL_HOST}
            - CONSUL_PORT=${CONSUL_PORT}
            - PATH_PREFIX=${PATH_PREFIX}
        ports:
            - 8083:8083
        networks:
            - microservices
    demo-application-8084:
        image: markoniemi/traefik-consul-demo
        environment:
            - PORT=8084
            - CONSUL_HOST=${CONSUL_HOST}
            - CONSUL_PORT=${CONSUL_PORT}
            - PATH_PREFIX=${PATH_PREFIX}
        ports:
            - 8084:8084
        networks:
            - microservices
    portainer:
        image: portainer/portainer
        command: -H unix:///var/run/docker.sock
        restart: always
        ports:
            - 9000:9000
            - 8000:8000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock            
networks:
    microservices:
        driver: bridge
